EVENT_API = 'https://api.github.com/repos/vocaned/webhook/events'
POLL_INTERVAL = 300 # In seconds. Minimum poll interval is dynamically returned by GitHub API and will override this if the value is set too low (usually 60 seconds during normal server load)
GH_TOKEN = ''
DISCORD_WEBHOOK = ''

REPO_BLACKLIST = [ ]
EVENT_BLACKLIST = [ ]

USER_WHITELIST = [ ]
